/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mail.view;

import java.awt.BorderLayout;
import java.awt.Color;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import mail.presenter.ListaDeMensagens;

/**
 * Esta classe faz parte de um app de troca de mensagens.
 * Ela contem dois botoes e um JList para a listar as mensagens recebidas.
 * @author prof-valmor
 */
public class Inbox extends javax.swing.JPanel {

    /**
     * Creates new form Inbox
     */
    public Inbox() {
        initComponents();
        setBackground(Color.yellow);
        jList2.setListData(ListaDeMensagens.getInstance().getListaDeMensagens());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setLayout(new java.awt.BorderLayout());

        jButton2.setText("EXCLUIR");
        add(jButton2, java.awt.BorderLayout.PAGE_END);

        jButton1.setText("NOVA MENSAGEM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setViewportView(jList2);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDialog dlg;
        dlg = new JDialog();
        dlg.setTitle("Preencha para enviar a mensagem.");
        dlg.setLayout(new BorderLayout());
        dlg.add(new JTextField("Destinatario:"), BorderLayout.NORTH);
        dlg.add(new JTextArea("Mensagem"), BorderLayout.CENTER);
        dlg.add(new JButton("Enviar"), BorderLayout.SOUTH);
        dlg.pack();
        dlg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
