/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypaint;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author old_adam
 */
public class Janela1 extends javax.swing.JFrame {

    private MyPanel painelDesenho;
    /**
     * Creates new form Janela1
     */
    public Janela1() {
        //
        initComponents();
        //
        setBackground(Color.CYAN);
        setSize(600, 600);
        
        painelDesenho = new MyPanel();
        painelDesenho.setSize(getWidth(), getHeight()-jPanel2.getHeight());
        painelDesenho.setBackground(Color.white);
        add(painelDesenho, BorderLayout.CENTER);
        //
        
        btAddTriangulo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                painelDesenho.add(new Triangulo(new Point(50, 50), new Point(50,100), new Point(200,100)));
            }
        });
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btAddQuadrado = new javax.swing.JButton();
        btAddTriangulo = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        myPanel1 = new mypaint.MyPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyPaint");
        setSize(new java.awt.Dimension(600, 600));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btAddQuadrado.setText("Quadrado");
        btAddQuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddQuadradoActionPerformed(evt);
            }
        });
        jPanel2.add(btAddQuadrado);

        btAddTriangulo.setText("Triangulo");
        jPanel2.add(btAddTriangulo);

        btClear.setText("Clear");
        jPanel2.add(btClear);

        btDelete.setText("X");
        jPanel2.add(btDelete);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(myPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /**
      * Evento de click no botao btAddQuadrado.
      * @param evt 
      */
    private void btAddQuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddQuadradoActionPerformed
        painelDesenho.add(new Quadrado(50, 50, 200));
    }//GEN-LAST:event_btAddQuadradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddQuadrado;
    private javax.swing.JButton btAddTriangulo;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JPanel jPanel2;
    private mypaint.MyPanel myPanel1;
    // End of variables declaration//GEN-END:variables
}
